#Basic Techniques for Implementing Data Structures

#Structured Programming

Structured programming is a programming paradigm aimed at improving the clarity, quality, and development time of a computer program. It uses control structures like sequences, loops, and conditionals to solve problems in a logical and organized manner.

In [1]:
# Structured programming example: Factorial calculation using recursion
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)

result = factorial(5)
print("Factorial of 5 is:", result)

Factorial of 5 is: 120


#Object-Oriented Programming (OOP)

OOP is a programming paradigm based on the concept of "objects," which can contain data in the form of fields (attributes) and code in the form of procedures (methods). It enables modeling real-world entities using classes and objects.


In [2]:
# Object-oriented programming example: Simple Bank Account System
class BankAccount:
    def __init__(self, account_number, balance=0):
        self.account_number = account_number
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
        print(f"Deposited ${amount}. New balance: ${self.balance}")

    def withdraw(self, amount):
        if self.balance >= amount:
            self.balance -= amount
            print(f"Withdrew ${amount}. New balance: ${self.balance}")
        else:
            print("Insufficient funds")

# Usage of BankAccount class
acc1 = BankAccount("123456789")
acc1.deposit(1000)
acc1.withdraw(500)

Deposited $1000. New balance: $1000
Withdrew $500. New balance: $500


#Abstract Data Types (ADTs)

ADTs are mathematical models used to describe the logical properties of a data type independent of its implementation. It specifies a set of operations and their behavior without specifying how these operations will be implemented.



In [1]:
# Example of abstract data type in Python using classes
class Stack:
    def __init__(self):
        self.items = []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        return self.items.pop()

# Using the Stack ADT
stack = Stack()
stack.push(10)
stack.push(20)
print(stack.pop())  # Output: 20

20


#Programming Language Independence from Data Structure Users
Data structures should provide interfaces that are language-independent, allowing users to interact with them using different programming languages without modifying the underlying structure.

In [ ]:
#include <iostream>
#include <stack>
#include <string>
#include <sstream>
#include <cstdlib>
#include <cstring>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>

#define PORT 8080

int main() {
    int server_fd, new_socket, valread;
    struct sockaddr_in address;
    int opt = 1;
    int addrlen = sizeof(address);

    std::stack<int> my_stack;

    // Creating socket file descriptor
    if ((server_fd = socket(AF_INET, SOCK_STREAM, 0)) == 0) {
        perror("socket failed");
        exit(EXIT_FAILURE);
    }

    // Forcefully attaching socket to the port 8080
    if (setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT,
                                                  &opt, sizeof(opt))) {
        perror("setsockopt");
        exit(EXIT_FAILURE);
    }
    address.sin_family = AF_INET;
    address.sin_addr.s_addr = INADDR_ANY;
    address.sin_port = htons(PORT);

    // Forcefully attaching socket to the port 8080
    if (bind(server_fd, (struct sockaddr *)&address,
                                 sizeof(address))<0) {
        perror("bind failed");
        exit(EXIT_FAILURE);
    }
    if (listen(server_fd, 3) < 0) {
        perror("listen");
        exit(EXIT_FAILURE);
    }
    if ((new_socket = accept(server_fd, (struct sockaddr *)&address,
                       (socklen_t*)&addrlen))<0) {
        perror("accept");
        exit(EXIT_FAILURE);
    }

    // Handle client requests
    while (true) {
        char buffer[1024] = {0};
        valread = read(new_socket, buffer, 1024);
        std::string command(buffer);

        if (command.find("push") != std::string::npos) {
            // Extract the number to push onto stack
            int num = std::stoi(command.substr(5));
            my_stack.push(num);
            send(new_socket, "Pushed to stack", strlen("Pushed to stack"), 0);
        } else if (command == "pop") {
            if (!my_stack.empty()) {
                int top = my_stack.top();
                my_stack.pop();
                std::string response = "Popped from stack: " + std::to_string(top);
                send(new_socket, response.c_str(), response.length(), 0);
            } else {
                send(new_socket, "Stack is empty", strlen("Stack is empty"), 0);
            }
        }
    }

    return 0;

#Platform Independence
Data structures should be designed to work efficiently across different hardware and software platforms, maintaining consistent performance and behavior.

In [ ]:
!pip install boto3

In [ ]:
import boto3

# AWS credentials and S3 bucket name
AWS_ACCESS_KEY = 'your_access_key'
AWS_SECRET_KEY = 'your_secret_key'
BUCKET_NAME = 'your_bucket_name'

def upload_to_s3(file_path, object_name):
    s3_client = boto3.client('s3', aws_access_key_id=AWS_ACCESS_KEY,
                             aws_secret_access_key=AWS_SECRET_KEY)
    try:
        response = s3_client.upload_file(file_path, BUCKET_NAME, object_name)
        print("File uploaded successfully to S3")
    except Exception as e:
        print("Upload failed:", e)

def download_from_s3(object_name, target_path):
    s3_client = boto3.client('s3', aws_access_key_id=AWS_ACCESS_KEY,
                             aws_secret_access_key=AWS_SECRET_KEY)
    try:
        s3_client.download_file(BUCKET_NAME, object_name, target_path)
        print("File downloaded successfully from S3")
    except Exception as e:
        print("Download failed:", e)

# Usage example: Upload and download a file to/from S3
upload_to_s3('local_file.txt', 'remote_file.txt')
download_from_s3('remote_file.txt', 'downloaded_file.txt')

#Concurrency Control
Concurrency control techniques manage simultaneous execution of multiple threads or processes accessing shared resources to prevent race conditions and ensure data consistency.

In [3]:
import threading
import queue
import time

# Global thread-safe queue
my_queue = queue.Queue()

def producer():
    for i in range(5):
        item = f"Item {i}"
        my_queue.put(item)
        print(f"Produced: {item}")
        time.sleep(0.5)

def consumer():
    for i in range(5):
        if not my_queue.empty():
            item = my_queue.get()
            print(f"Consumed: {item}")
            my_queue.task_done()
        time.sleep(1)

# Create producer and consumer threads
producer_thread = threading.Thread(target=producer)
consumer_thread = threading.Thread(target=consumer)

# Start threads
producer_thread.start()
consumer_thread.start()

# Wait for threads to complete
producer_thread.join()
consumer_thread.join()

print("All tasks completed")

Produced: Item 0
Consumed: Item 0
Produced: Item 1
Produced: Item 2Consumed: Item 1

Consumed: Item 2
Produced: Item 3
Produced: Item 4Consumed: Item 3

Consumed: Item 4
All tasks completed


#Data Protection
Data protection involves implementing security measures to ensure confidentiality, integrity, and availability of data within data structures, protecting against unauthorized access or modifications.

In [5]:
import threading

class SecureDictionary:
    def __init__(self):
        self._data = {}
        self._lock = threading.Lock()

    def set(self, key, value):
        with self._lock:
            self._data[key] = value

    def get(self, key):
        with self._lock:
            return self._data.get(key, None)

# Usage example
secure_dict = SecureDictionary()

secure_dict.set('key1', 'value1')
secure_dict.set('key2', 'value2')

print(secure_dict.get('key1'))  # Output: 'value1'
print(secure_dict.get('key3'))  # Output: None

value1
None


#Encapsulation Levels
Encapsulation refers to restricting access to certain components of an object, allowing controlled interactions with its internal state and behavior at different levels of abstraction.

In [6]:
class Stack:
    def __init__(self):
        self._items = []

    def push(self, item):
        self._items.append(item)

    def pop(self):
        if not self.is_empty():
            return self._items.pop()
        else:
            raise IndexError("Stack is empty")

    def is_empty(self):
        return len(self._items) == 0

    def __len__(self):
        return len(self._items)

# Usage example
stack = Stack()

stack.push(10)
stack.push(20)

print(stack.pop())  # Output: 20
print(len(stack))  # Output: 1

20
1


#Data Structures in Primary, Secondary, and Tertiary Memory
Data structures are optimized differently based on their storage location, whether in primary (RAM), secondary (disk), or tertiary (external storage) memory, to achieve performance and scalability goals.

In [11]:
class LRUCache:
    def __init__(self, capacity):
        self._capacity = capacity
        self._cache = {}
        self._access_order = []

    def get(self, key):
        if key in self._cache:
            # Update access order (move key to the end)
            self._access_order.remove(key)
            self._access_order.append(key)
            return self._cache[key]
        else:
            return None

    def set(self, key, value):
        if len(self._cache) >= self._capacity:
            # Evict least recently used item
            oldest_key = self._access_order.pop(0)
            del self._cache[oldest_key]

        self._cache[key] = value
        if key in self._access_order:
            self._access_order.remove(key)
        self._access_order.append(key)

# Usage example
lru_cache = LRUCache(2)

lru_cache.set('key1', 'value1')
lru_cache.set('key2', 'value2')

print(lru_cache.get('key1'))  # Output: 'value1'
lru_cache.set('key3', 'value3')  # Evicts 'key2'
print(lru_cache.get('key2'))  # Output: None (evicted)


value1
None


#Data Structures on GPUs
Utilizing data structures on GPUs involves leveraging the parallel processing capabilities of graphics processing units (GPUs) to accelerate computations and data-intensive tasks.

In [13]:
import numpy as np
import multiprocessing

def matrix_multiply(A, B, result_queue):
    C = np.dot(A, B)
    result_queue.put(C)

if __name__ == "__main__":
    A = np.random.rand(3, 3)
    B = np.random.rand(3, 3)

    result_queue = multiprocessing.Queue()
    process = multiprocessing.Process(target=matrix_multiply, args=(A, B, result_queue))
    process.start()
    process.join()

    result = result_queue.get()
    print("Matrix multiplication result:")
    print(result)

Matrix multiplication result:
[[1.56491504 1.04061374 1.45570704]
 [0.82017723 0.61069194 0.89382184]
 [1.0443001  0.71467453 1.05603249]]
