#3. Multidimensional arrays: Tensors
#### 3.1. Definitions

*Tensor*:
- A tensor is a generalized concept of vectors and matrices to higher dimensions.
- Tensors can represent data in higher-dimensional spaces, which is essential for many machine learning and deep learning applications.
- Tensors are used extensively in frameworks like TensorFlow and PyTorch.

*Order (Rank)*:
- The number of dimensions a tensor has.
- Scalar: A single number (0-dimensional tensor).
- Vector: A 1-dimensional tensor.
- Matrix: A 2-dimensional tensor.
- Higher-order tensors: 3D tensors, 4D tensors, and so on.

*Shape*:
- The shape of a tensor is a tuple representing the size of each dimension.

*Examples*:
- Scalar: 3 (shape: ())
- Vector: [1, 2, 3] (shape: (3,))
- Matrix: [[1, 2], [3, 4]] (shape: (2, 2))
- 3D Tensor: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]] (shape: (2, 2, 2))

#### 3.2. Creating a Tensor

Creating tensors in TensorFlow:

In [1]:
import tensorflow as tf

# Scalar
scalar = tf.constant(3)
print("Scalar:", scalar)

# Vector
vector = tf.constant([1, 2, 3])
print("Vector:", vector)

# Matrix
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)

# 3D Tensor
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Tensor:", tensor_3d)

# Higher-order Tensor
tensor_4d = tf.random.normal([3, 3, 3, 3])  # 4D tensor with random values
print("4D Tensor:", tensor_4d)

Scalar: tf.Tensor(3, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
3D Tensor: tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
4D Tensor: tf.Tensor(
[[[[ 0.21517427 -1.0674813  -1.1855551 ]
   [-0.14382572 -1.7070622  -0.5960419 ]
   [ 0.37751815 -0.19666176  0.36918983]]

  [[ 0.4442822  -2.4559412   1.0381485 ]
   [-0.43373248 -1.2615013  -1.602615  ]
   [ 0.6871438  -1.103767    0.13396183]]

  [[-0.12689644 -0.9184361  -0.65228003]
   [-0.36818498 -0.5314076  -0.63693506]
   [ 0.5960835  -1.203138   -0.2857015 ]]]


 [[[-0.34971705  0.15584742 -0.94834787]
   [ 1.4082457   0.33960432 -1.7262065 ]
   [-0.6975394   0.2157053   0.19664432]]

  [[-0.38300332  0.3243978  -0.9247898 ]
   [-0.2423386  -0.20037806  0.75627416]
   [ 0.5130751  -0.7681052   0.6779137 ]]

  [[-0.9280416   0.69160855  0.6707856 ]
   [ 0.03611741 -0.17550214  0.49705127]
   [-0.20699021  1.516

#### 3.3. Algorithms on Tensors

Tensors can be manipulated using a variety of operations. Here are some examples of common tensor operations and algorithms:

*Element-wise Operations*:

In [2]:
import tensorflow as tf

# Define two tensors
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

# Element-wise addition
add_result = tf.add(tensor_a, tensor_b)
print("Addition Result:\n", add_result)

# Element-wise multiplication
multiply_result = tf.multiply(tensor_a, tensor_b)
print("Multiplication Result:\n", multiply_result)

Addition Result:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Multiplication Result:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


*Matrix Multiplication*:


In [3]:
# Matrix multiplication (dot product)
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

matmul_result = tf.matmul(matrix_a, matrix_b)
print("Matrix Multiplication Result:\n", matmul_result)

Matrix Multiplication Result:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


*Transposing a Tensor*:


In [5]:
# Transpose a tensor
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
transpose_result = tf.transpose(matrix)
print("Transpose Result:\n", transpose_result)

Transpose Result:
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


*Reshaping a Tensor*:


In [6]:
#Reshape a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
reshape_result = tf.reshape(tensor, [3, 2])
print("Reshape Result:\n", reshape_result)

Reshape Result:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


*Reducing Operations*:


In [7]:
# Reducing a tensor along dimensions
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# Sum all elements
reduce_sum_result = tf.reduce_sum(tensor)
print("Reduce Sum Result:", reduce_sum_result)

# Sum along specific dimension
reduce_sum_axis_result = tf.reduce_sum(tensor, axis=0)
print("Reduce Sum along Axis 0 Result:", reduce_sum_axis_result)

Reduce Sum Result: tf.Tensor(21, shape=(), dtype=int32)
Reduce Sum along Axis 0 Result: tf.Tensor([5 7 9], shape=(3,), dtype=int32)


*Reducing Operations:*

In [8]:
# Reducing a tensor along dimensions
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

# Sum all elements
reduce_sum_result = tf.reduce_sum(tensor)
print("Reduce Sum Result:", reduce_sum_result)

# Sum along specific dimension
reduce_sum_axis_result = tf.reduce_sum(tensor, axis=0)
print("Reduce Sum along Axis 0 Result:", reduce_sum_axis_result)

Reduce Sum Result: tf.Tensor(21, shape=(), dtype=int32)
Reduce Sum along Axis 0 Result: tf.Tensor([5 7 9], shape=(3,), dtype=int32)


3.3.1. Operaciones Elementales


Element by element op.

In [17]:
import tensorflow as tf

# Definir dos tensores
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

# Suma elemento por elemento
add_result = tf.add(tensor_a, tensor_b)
print("Sum result:\n", add_result)

# Multiplicación elemento por elemento
multiply_result = tf.multiply(tensor_a, tensor_b)
print("Multiplication result:\n", multiply_result)

Sum result:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Multiplication result:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


Matrix multiplication:

In [18]:
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

matmul_result = tf.matmul(matrix_a, matrix_b)
print(matmul_result)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


Tensor transposition:

In [22]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
transpose_result = tf.transpose(matrix)
print(transpose_result)

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


Tensor reestructuration:

In [21]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
reshape_result = tf.reshape(tensor, [3, 2])
print(reshape_result)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


Reduction op.

In [23]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])

reduce_sum_result = tf.reduce_sum(tensor)
print("Reduce sum result", reduce_sum_result)

reduce_sum_axis_result = tf.reduce_sum(tensor, axis=0)
print("Reduce sum result across the axis 0:", reduce_sum_axis_result)

Reduce sum result tf.Tensor(21, shape=(), dtype=int32)
Reduce sum result across the axis 0: tf.Tensor([5 7 9], shape=(3,), dtype=int32)


Tensor concatenation:

In [24]:
tensor1 = tf.constant([[1, 2], [3, 4]])
tensor2 = tf.constant([[5, 6], [7, 8]])

concat_result = tf.concat([tensor1, tensor2], axis=0)
print("Result of the tensor concatenation across the axis 0:\n", concat_result)

concat_result_axis1 = tf.concat([tensor1, tensor2], axis=1)
print("Result of the tensor concatenation across the axis 1:\n", concat_result_axis1)

Result of the tensor concatenation across the axis 0:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]
 [7 8]], shape=(4, 2), dtype=int32)
Result of the tensor concatenation across the axis 1:
 tf.Tensor(
[[1 2 5 6]
 [3 4 7 8]], shape=(2, 4), dtype=int32)


Tensor segmentation:

In [25]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

split_result = tf.split(tensor, num_or_size_splits=3, axis=0)
print("Result of the tensor segmentation in three parts across the axis 0:\n", split_result)

Result of the tensor segmentation in three parts across the axis 0:
 [<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>, <tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[4, 5, 6]], dtype=int32)>, <tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[7, 8, 9]], dtype=int32)>]


In [26]:
import tensorflow as tf
import numpy as np

# Function to initialize a tensor
def create_tensor(shape, value=0.0):
    return tf.Variable(tf.fill(shape, value), dtype=tf.float32)

# 2D Convolution Algorithm (without using tf.nn.conv2d)
def convolution_2d(input_tensor, kernel):
    input_shape = input_tensor.shape
    kernel_shape = kernel.shape
    output_shape = (input_shape[0] - kernel_shape[0] + 1, input_shape[1] - kernel_shape[1] + 1)
    output = create_tensor(output_shape)

    for i in range(output_shape[0]):
        for j in range(output_shape[1]):
            output[i, j].assign(tf.reduce_sum(input_tensor[i:i+kernel_shape[0], j:j+kernel_shape[1]] * kernel))

    return output

# Backpropagation algorithm for a single-layer neural network (without using tf.GradientTape)
def simple_backpropagation(X, y, weights, bias, learning_rate):
    m = X.shape[0]

    # Forward pass
    Z = tf.matmul(X, weights) + bias
    A = tf.nn.sigmoid(Z)
    loss = tf.reduce_mean(tf.square(A - y))

    # Backward pass (calculate gradients)
    dZ = A - y
    dW = tf.matmul(tf.transpose(X), dZ) / m
    dB = tf.reduce_mean(dZ, axis=0)  # Calculate the gradient for the bias correctly

    # Update parameters
    weights.assign_sub(learning_rate * dW)
    bias.assign_sub(learning_rate * tf.reshape(dB, bias.shape))  # Ensure dB shape matches bias shape

    return loss

# SVD (Singular Value Decomposition) algorithm
def svd_decomposition(tensor):
    tensor = tf.cast(tensor, tf.float32)
    s, u, v = tf.linalg.svd(tensor)
    return s, u, v

# Example usage of the algorithms

# Creating example tensors
input_tensor = tf.constant([
    [1, 2, 3, 0],
    [4, 5, 6, 0],
    [7, 8, 9, 0],
    [0, 0, 0, 0]
], dtype=tf.float32)

kernel = tf.constant([
    [1, 0],
    [0, -1]
], dtype=tf.float32)

# Apply convolution
conv_result = convolution_2d(input_tensor, kernel)
print("2D Convolution Result:\n", conv_result.numpy())

# Creating data for backpropagation
X = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], dtype=tf.float32)
y = tf.constant([[0.0], [1.0], [0.0]], dtype=tf.float32)
weights = create_tensor([2, 1], value=0.1)
bias = create_tensor([1], value=0.1)

# Apply backpropagation
loss = simple_backpropagation(X, y, weights, bias, learning_rate=0.1)
print("Loss after backpropagation:", loss.numpy())

# Creating tensor for SVD
tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=tf.float32)

# Apply SVD
s, u, v = svd_decomposition(tensor)
print("Singular Values:\n", s.numpy())
print("U Matrix:\n", u.numpy())
print("V Matrix:\n", v.numpy())

2D Convolution Result:
 [[-4. -4.  3.]
 [-4. -4.  6.]
 [ 7.  8.  9.]]
Loss after backpropagation: 0.34839103
Singular Values:
 [1.6848103e+01 1.0683696e+00 2.8763120e-07]
U Matrix:
 [[ 0.21483716  0.8872305  -0.40824857]
 [ 0.5205872   0.24964423  0.8164965 ]
 [ 0.8263376  -0.3879429  -0.4082481 ]]
V Matrix:
 [[ 0.47967106 -0.77669096  0.40824836]
 [ 0.5723676  -0.07568647 -0.81649655]
 [ 0.6650643   0.62531805  0.40824822]]
